site_name: Front Study
theme: readthedocs

pages:
  - Home: README.md
  - CSS:
      - "Grid": "css/grid.md"
  - Interview:
      - "DocType": "interview/doctype.md"
  - React:
      - "Introduce": "react/about.md"
      - "Start": "react/start.md"
      - "Component": "react/component.md"
      - "JSX": "react/jsx.md"
      - "State": "react/state.md"
      - "Props": "react/props.md"
      - "LifeCycle": "react/lifecycle.md"
      - "DOM": "react/dom.md"
      - "HOC": "react/hoc.md"
  - React Library:
      - "Immutable": "react-library/immutable.md"
      - "Axios": "react-library/axios.md"
  - React Styling:
      - "Scss": "react-styling/sass.md"
      - "Module": "react-styling/module.md"
      - "Styled Components": "react-styling/styled-components"
