site_name: Front Study
theme: readthedocs

pages:
  - Home: README.md
  - JS:
      - "Promise": "js/promise,md"
  - CSS:
      - "Flex": "css/flex.md"
      - "Grid": "css/grid.md"
  - Interview:
      - "DocType": "interview/doctype.md"
      - "Pipline": "interview/pipline.md"
  - React:
      - "Introduce": "react/about.md"
      - "Start": "react/start.md"
      - "Component": "react/component.md"
      - "JSX": "react/jsx.md"
      - "State": "react/state.md"
      - "Props": "react/props.md"
      - "LifeCycle": "react/lifecycle.md"
      - "DOM": "react/dom.md"
      - "HOC": "react/hoc.md"
      - "Context": "react/context.md"
      - "Code Spliting": "react/code-spliting.md"
      - "Hooks": "react/hooks.md"
  - React Library:
      - "Immutable": "react-library/immutable.md"
      - "Axios": "react-library/axios.md"
      - "Redux": "react-library/redux.md"
      - "Router": "react-library/router.md"
  - React Styling:
      - "Scss": "react-styling/sass.md"
      - "Module": "react-styling/module.md"
      - "Styled Components": "react-styling/styled-components"
  - Tool:
      - "Sublime Text": "tool/sunlime-text.md"
      - "Z Shell": "tool/zsh.md"
  - Server Tool:
      - "Nginx": "server-tool/nginx.md"
