site_name: Front Study
theme: readthedocs

pages:
  - Home: README.md
  - Algorithm:
      - "Search & Sort": "algorithm/search-sort.md"
      - "Linked List": "algorithm/linked-list.md"
      - "Caching": "algorithm/caching.md"
      - "Tree": "algorithm/tree.md"
      - "Heep": "algorithm/heep.md"
      - "Graph": "algorithm/graph.md"
      - "String": "algorithm/string.md"
      - "Dynamic": "algorithm/dynamic.md"
  - Front Interview:
      - "ECMA": "front_interview/ecma.md"
      - "Doctype": "front_interview/doctype.md"
      - "meta": "front_interview/meta.md"
      - "Browser Rendering": "front_interview/browser-rendering.md"
      - "Oop": "front_interview/oop.md"
  - Javascript:
      - "ES6": "javascript/es6.md"
      - "Async": "javascript/async.md"
      - "Promise": "javascript/promise.md"
      - "Symbolic Iterator Generator": "javascript/symbol-iterator-generator.md"
      - "Babel": "javascript/babel.md"
      - "Webpack": "javascript/webpack.md"
      - "Memory Leak": "javascript/memory-leak.md"
  - CSS:
      - "Flex": "css/flex.md"
      - "Grid": "css/grid.md"
      - "Sass": "css/sass.md"
      - "Styled Component": "css/styled-components.md"
      - "Module": "css/module.md"
      - "Postcss": "css/Postcss.md"
  - Node.JS:
      - "Koa": "nodeJS/koa.md"
      - "Cache Control": "nodeJS/cache-control.md"
      - "Express Rate Limit": "nodeJS/express-rate-limit.md"
      - "Express Slow Down": "nodeJS/express-slow-down.md"
      - "Helmet": "nodeJS/helmet.md"
  - React:
      - "About": "react/about.md"
      - "Start": "react/start.md"
      - "JSX": "react/jsx.md"
      - "Props": "react/props.md"
      - "State": "react/state.md"
      - "Lifecycle": "react/lifecycle.md"
      - "Component": "react/component.md"
      - "Dom": "react/dom.md"
      - "Hoc": "react/hoc.md"
      - "Context": "react/context.md"
      - "Axios": "react/axios.md"
      - "Immutable": "react/immutable.md"
      - "Redux": "react/redux.md"
      - "Router": "react/router.md"
      - "Code Spliting": "react/code-spliting.md"
      - "Server": "react/server.md"
      - "Hooks": "react/hooks.md"
      - "Manifest Servicesworker": "react/manifest-servicesworker.md"
  - React Typescript:
      - "About": "react_typescript/about.md"
      - "Start": "react_typescript/start.md"
      - "React": "react_typescript/react.md"
      - "Hooks": "react_typescript/hooks.md"
      - "Redux": "react_typescript/redux.md"
      - "Rollup": "react_typescript/rollup.md"
      - "Redux Saga": "react_typescript/redux-saga.md"
  - Security:
      - "JWT": "security/jwt.md"
      - "HSM": "security/hsm.md"
  - ETC:
      - "Nginx": "etc/nginx.md"
      - "OAuth": "etc/OAuth.md"
      - "Pipline": "etc/pipline.md"
      - "Sublime Text": "etc/sublime-text.md"
      - "Zsh": "etc/zsh.md"
      - "Firebase Dynamic Link": "etc/firebase-dynamic-link.md"
