site_name: Front Study
theme: readthedocs

pages:
  - Home: README.md
  - Interview:
      - "DocType": "interview/doctype.md"
  - React:
      - "Introduce": "react/about.md"
      - "Component": "react/component.md"
      - "JSX": "react/jsx.md"
      - "Props": "react/props.md"
      - "State": "react/state.md"
