site_name: Front Study
theme: readthedocs

pages:
  - Home: README.md
  - Interview:
      - "DocType": "interview/doctype.md"
  - React:
      - "Introduce": "react/about.md"
      - "Start": "react/start.md"
      - "Component": "react/component.md"
      - "JSX": "react/jsx.md"
      - "State": "react/state.md"
      - "Props": "react/props.md"
      - "LifeCycle": "react/lifecycle.md"
      - "DOM": "react/dom.md"
  - React Library:
      - "Immutable": "react-library/immutable.md"
  - React Styling:
      - "Scss": "react-styling/sass.md"
